backend/Dockerfile

Сжатие конечного Docker-образа

Dockerfile refacror

---

backend/Dockerfile

Reverts Diacrome/super-scoring#12

Revert "Dockerfile refacror"

---

backend/init.sql

https://trello.com/c/jD7Ebn4o/20-ss-11-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C-sql-%D1%81%D1%83%D1%89%D0%BD%D0%BE%D1%81%D1%82%D0%B8-%D0%BD%D0%B0-%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%B5-%D0%BC%D0%B8%D1%80%D0%BE

SS-11 create database initialization

---

backend/src/main/java/ru/hh/superscoring/entity/Test.java

https://trello.com/c/ehngLPHS/29-ss-20-%D0%B8%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%83-backend-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5-%D0%B2%D0%BC%D0%B5%D1%80%D0%B6%D0%B8%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-ss-11  исправление backend после merge SS-11

SS-20 исправление backend после merge SS-11

---

backend/init.sql
backend/src/main/java/ru/hh/superscoring/entity/Test.java

https://trello.com/c/ehngLPHS/29-ss-20-%D0%B8%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%83-backend-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5-%D0%B2%D0%BC%D0%B5%D1%80%D0%B6%D0%B8%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-ss-11 Ss-20 SS-20 исправление backend после merge SS-11 дубль 2

Ss-20 SS-20 исправление backend после merge SS-11 дубль 2

---

backend/src/main/java/ru/hh/superscoring/resource/ExampleResource.java
backend/src/test/java/ExampleResourceTest.java
backend/src/test/java/ExampleServerAwareBeanTest.java
backend/src/test/resources/service-test.properties

https://trello.com/c/085YbVHM/37-ss-28-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D1%82%D0%B8%D1%82%D1%8C-%D1%8E%D0%BD%D0%B8%D1%82-%D1%82%D0%B5%D1%81%D1%82%D1%8B

SS-28: test restored

---

backend/README.md
backend/init.sql
backend/src/main/java/ru/hh/superscoring/config/CommonConfig.java
backend/src/main/java/ru/hh/superscoring/dao/AuthDao.java
backend/src/main/java/ru/hh/superscoring/dao/QuestionDao.java
backend/src/main/java/ru/hh/superscoring/entity/Question.java
backend/src/main/java/ru/hh/superscoring/resource/QuestionResource.java
backend/src/main/java/ru/hh/superscoring/service/AuthService.java
backend/src/main/java/ru/hh/superscoring/service/QuestionService.java

https://trello.com/c/KsucpqD7/48-ss-39-%D1%83%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D0%B0-%D0%B8%D0%B7-%D0%BD%D0%B0%D0%B1%D0%BE%D1%80%D0%B0-%D1%82%D0%B5%D1%81%D1%82%D0%B0 SS-39 Added the ability to set the inactive status for a question

SS-39 Added the ability to set the inactive status for a question

---

backend/src/main/java/ru/hh/superscoring/dao/QuestionDao.java

SS-42 Bug fix

---

backend/README.md
backend/src/main/java/ru/hh/superscoring/config/CommonConfig.java
backend/src/main/java/ru/hh/superscoring/dao/AnswerDao.java
backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
backend/src/main/java/ru/hh/superscoring/dto/StatusDto.java
backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
backend/src/main/java/ru/hh/superscoring/service/StatusService.java

SS-14 Add status

---

backend/init.sql
backend/src/main/java/ru/hh/superscoring/dao/TestDao.java
backend/src/main/java/ru/hh/superscoring/dto/TestDto.java
backend/src/main/java/ru/hh/superscoring/entity/Test.java
backend/src/main/java/ru/hh/superscoring/resource/TestPassResource.java
backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
backend/src/main/java/ru/hh/superscoring/service/TestService.java

Карточка Trello:
https://trello.com/c/awtxBgqJ
Кроме выключения сделал включение теста отдельной ручкой.
Изменения затронули: создание теста (по умолчанию создается активным),информацию о тесте и запуск теста (создание прохождения).
Не вполне ясно, что делать, если тест отключен, скажем, во время тестирования кем-то. Нужно ли добавлять проверку на включенность теста?

SS-40 Деактивация/активация теста

---

backend/src/main/java/ru/hh/superscoring/service/QuestionService.java

https://trello.com/c/1tHfPmeq/59-ss-49-фикс-ss-36

SS-49 Fix method in SS-36

---

backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
backend/src/main/java/ru/hh/superscoring/resource/AnswerResource.java
backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
backend/src/main/java/ru/hh/superscoring/util/JsonValidator.java

https://trello.com/c/Ib6iaHxq 
[SS-33] block [SS-32] Принимать answer - валидировать ответ по схеме

SS-33 Added answer verification

---

backend/src/main/java/ru/hh/superscoring/service/QuestionService.java

Ссылка на карточку trello:
https://trello.com/c/4cG64Soy
P.S. Либо я неверно понял задачу, либо она была очень короткой.

SS-48 Answer validation in question adding

---

tests/tests.json

SS-55 Add auth autotest

---

backend/src/main/java/ru/hh/superscoring/util/JsonValidator.java
backend/src/test/java/JsonValidatorTest.java

SS-47 Added unit tests for JsonValidator

---

backend/src/main/java/ru/hh/superscoring/resource/TestPassResource.java
backend/src/main/java/ru/hh/superscoring/service/TestPassService.java

SS-64 Refactoring of start test (fix ambiguous message)

---

backend/init.sql
tests/tests.json

https://trello.com/c/rgvNyWOu
Добавлены автотесты для ручек старта тестирования и отказа от тестирования

SS-63 Added start and cancel autotests

---

backend/src/main/java/ru/hh/superscoring/util/JsonValidator.java
backend/src/test/java/JsonValidatorTest.java

SS-65 added validation of the RANKING question type and tests for it

---

backend/README.md
backend/src/main/java/ru/hh/superscoring/dto/StatusDto.java
backend/src/main/java/ru/hh/superscoring/service/StatusService.java

SS-79 Information about the user's role has been added to getting the status

---

backend/src/main/java/ru/hh/superscoring/service/AnswerService.java

Карточка trello:
https://trello.com/c/T6iuj8yr/78-ss-68
Эта задача решилась одной строкой кода, поскольку ранее уже Екатерина добавила веса, а Кирилл - подсчет общей суммы.

SS-68 Add weights to test results

---

backend/src/main/java/ru/hh/superscoring/resource/TestPassResource.java
backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
backend/src/main/java/ru/hh/superscoring/service/TestService.java

SS-89 refactoring has been performed, the exception is triggered immediately after the error is detected

---

backend/init.sql
backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
backend/src/main/java/ru/hh/superscoring/entity/Test.java
backend/src/main/java/ru/hh/superscoring/resource/AnswerResource.java
backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
backend/src/main/java/ru/hh/superscoring/util/Exceptions/TestPassTimeoutException.java
backend/src/main/java/ru/hh/superscoring/util/TestPassStatus.java

SS-78 Add timeout check in test pass

---

backend/src/main/java/ru/hh/superscoring/resource/AnswerResource.java
backend/src/main/java/ru/hh/superscoring/resource/TestPassResource.java
backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
backend/src/main/java/ru/hh/superscoring/service/TestService.java
backend/src/main/java/ru/hh/superscoring/util/exceptions/TestNoFilledException.java
backend/src/main/java/ru/hh/superscoring/util/exceptions/TestPassTimeoutException.java

SS-93 Refactor exceptions folder

---

backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
backend/src/main/java/ru/hh/superscoring/dto/TestPassBoardDto.java
backend/src/main/java/ru/hh/superscoring/dto/TestPassDto.java
backend/src/main/java/ru/hh/superscoring/resource/TestPassResource.java
backend/src/main/java/ru/hh/superscoring/service/TestPassService.java

SS-85 added user receiving a list of all his passes by test id

---

backend/src/main/java/ru/hh/superscoring/resource/QuestionResource.java
backend/src/main/java/ru/hh/superscoring/resource/TestPassResource.java
backend/src/main/java/ru/hh/superscoring/resource/TestResource.java

https://trello.com/c/EGp1QMlS - Задокументировать ручки:
/test/get-tests
/test/all-tests-for-user
/test/results/{pass_id}
/cancel
/question/all-questions-in-test/{testId}
/question/all-questions
Попутно 
исправлена 500 ошибка при запросе к ручкам /question/all-questions-in-test/{testId} и /question/all-questions. (не указан MediaType); 
переименован метод для получения таблицы лидеров getLeaderBoard (ранее называвшийся startTest, что не отражало его функции)

SS-94 Added api description for some methods

---

backend/init.sql
backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
backend/src/main/java/ru/hh/superscoring/dto/TestPassBoardDto.java
backend/src/main/java/ru/hh/superscoring/dto/TestPassDto.java
backend/src/main/java/ru/hh/superscoring/dto/UserPassDto.java
backend/src/main/java/ru/hh/superscoring/entity/User.java
backend/src/main/java/ru/hh/superscoring/resource/TestPassResource.java
backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
backend/src/main/java/ru/hh/superscoring/service/TestPassService.java

SS-96 added user information to the test results

---

backend/init.sql
backend/src/main/java/ru/hh/superscoring/dao/QualificationDao.java
backend/src/main/java/ru/hh/superscoring/entity/Qualification.java
backend/src/main/java/ru/hh/superscoring/service/AnswerService.java

SS-99 added a business English test and changed the algorithm for calculating the skill level

---

backend/README.md
backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
backend/src/main/java/ru/hh/superscoring/service/TestService.java

https://trello.com/c/YFqTvmH5 - [SS-95] Проверить при создании теста установку времени прохождения.
Параметры attemptQuantity, repeatInterval и timeLimit передаются при создании теста

SS-95 Added parametres for request to create a test

---

backend/src/main/java/ru/hh/superscoring/dao/QualificationDao.java

SS-101 bag fix

---

frontend/src/components/QuestionForm.tsx
frontend/src/hooks/useCancelPass.ts
frontend/src/styles/App.css

SS-58 Add cancel pass button

---

frontend/src/functions/getDate.ts
frontend/src/hooks/useTestStart.ts
frontend/src/pages/HomeScreen.tsx
frontend/src/pages/TestInfo.tsx
frontend/src/styles/App.css
frontend/src/types/attempts.ts

SS-83 Add info about next attempt

---

frontend/src/components/TestCardComponent.tsx
frontend/src/pages/HomeScreen.tsx
frontend/src/styles/App.css
frontend/src/types/testCatalog.ts

SS-109 Add list of tests from server on HomeScreen

---

backend/init.sql
backend/src/main/java/ru/hh/superscoring/config/FreeMarkerConfiguration.java

SS-111 the number of questions of 4 tests has been set to 20, all passes in the database have been completed, the project settings have been fixed

---

backend/src/main/java/ru/hh/superscoring/dao/QuestionDistributionDao.java
backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
backend/src/main/java/ru/hh/superscoring/service/TestService.java
backend/src/main/java/ru/hh/superscoring/util/exceptions/DistributionNotFoundException.java

SS-104 Add distribution delete

---

backend/src/main/resources/templates/parts/common.ftlh

SS-120 Fix admin resource project name, link to home page

---

frontend/src/components/AuthForm.tsx
frontend/src/components/RegisterForm.tsx
frontend/src/functions/userRegister.ts
frontend/src/hooks/useFetchToken.ts
frontend/src/pages/LoginScreen.tsx
frontend/src/styles/App.css
frontend/src/types/login.ts

SS-116 Add register form

---

frontend/src/pages/Results.tsx
frontend/src/styles/App.css

SS-114 Add diagram distribution of results

---

frontend/package.json
frontend/src/components/QuestionContent.tsx
frontend/src/pages/TestScreen.tsx
frontend/src/styles/App.css
frontend/src/types/questions.ts
frontend/yarn.lock

SS-117 Add display audio content

---

frontend/public/index.html

SS-113 Add application title

---

frontend/Dockerfile
frontend/nginx.conf
frontend/src/components/QuestionContent.tsx
frontend/src/components/TestProgressBar.tsx
frontend/src/components/TestTimer.tsx
frontend/src/components/Timer.tsx
frontend/src/functions/getTimer.tsx
frontend/src/pages/TestScreen.tsx
frontend/src/routes/index.tsx
frontend/src/styles/App.css
frontend/src/types/testDescription.ts
frontend/src/types/testTimer.ts

SS-112 Add progress-bar and timer

---

backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
backend/src/main/java/ru/hh/superscoring/util/Chart.java

https://trello.com/c/hWHEtlw8 - Заменить столбчатую диаграмму в результатах теста на два столбца показывающих ваш и средний результат в процентах

SS-122 Added Two Сolumn Chart
